version: '3'
services:
 bitbucket:
  image: "atlassian/bitbucket-server:{{ BITBUCKET_VERSION }}"
  container_name: {{ BITBUCKET_CONTAINER_NAME }}
  restart: always
  ports:
   - "7990:7990"
   - "7999:7999"
  environment:
   - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
  volumes:
   - {{ BITBUCKET_VOLUME_NAME }}:/var/atlassian/application-data/bitbucket
  links:
   - db
 db:
  image: postgres:{{ POSTGRES_VERSION }}
  container_name: {{ POSTGRES_CONTAINER_NAME }}
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
   POSTGRES_USER: {{ POSTGRES_USER }}
   POSTGRES_DB: {{ POSTGRES_DB }}
   PGDATA: /var/lib/postgresql/data/pgdata
  volumes:
   - {{ POSTGRES_VOLUME_NAME }}:/var/lib/postgresql/data
volumes:
 {{ BITBUCKET_VOLUME_NAME }}:
  external:
   name: {{ BITBUCKET_VOLUME_NAME }}
 {{ POSTGRES_VOLUME_NAME }}:
  external:
   name: {{ POSTGRES_VOLUME_NAME }}